	<div class="navbar navbar-inverse" role="navigation">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<img src="/assets/images/logo.png" class="logo-png" alt="Angeles Verdes"></a>
			<a class="sidebar-toggle" style="display:<?php echo (@$this->dataUser['allwindow']) ? 'none': 'block';?>"><i class="icon-paragraph-justify2"></i></a>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-icons">
				<span class="sr-only">Toggle navbar</span>
				<i class="icon-grid3"></i>
			</button>
			<button type="button" class="navbar-toggle offcanvas">
				<span class="sr-only">Toggle navigation</span>
				<i class="icon-paragraph-justify2"></i>
			</button>
		</div>

		<ul class="nav navbar-nav navbar-right collapse" id="navbar-icons">
			<li class="user dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown">
					<img src="/images/icons/icon-user.png">
					<span><?php echo $this->dataUser['USUARIO']; ?></span>
					<i class="caret"></i>
				</a>
				<ul class="dropdown-menu dropdown-menu-right icons-right">
					<li><a href="javascript:recoverypass()"><i class="icon-user"></i> Cambiar Contraseña</a></li>
					<li><a href="/admin/main/logout"><i class="icon-exit"></i> Salir</a></li>
				</ul>
			</li>
		</ul>
	</div>