<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
	<title>Angeles Verdes - Siames</title>
	<link href="/libs/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/libs/css/londinium-theme.css" rel="stylesheet" type="text/css">
	<link href="/libs/css/styles.css" rel="stylesheet" type="text/css">
	<link href="/libs/css/icons.css" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
	<link href="/libs/fullcalendar/fullcalendar.css" rel="stylesheet" media="screen">
	<link href="/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">		
	<link href="/css/style.css" rel="stylesheet" media="screen">
</head>
<body>
	<!-- Page container -->
 	<div class="page-container">
		<?php echo $this->layout()->content; ?>
	</div>
	<!-- /page container -->

	<script type="text/javascript" src="/libs/js/jquery.min.js"></script>
	<script type="text/javascript" src="/libs/js/jquery-ui.min.js"></script>
	
	<script type="text/javascript" src="/libs/js/plugins/charts/sparkline.min.js"></script>

	<script type="text/javascript" src="/libs/js/plugins/forms/uniform.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/select2.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/inputmask.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/autosize.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/inputlimit.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/listbox.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/multiselect.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/validate.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/tags.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/switch.min.js"></script>
	
	<script type="text/javascript" src="/libs/js/plugins/forms/uploader/plupload.full.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/uploader/plupload.queue.min.js"></script>

	<script type="text/javascript" src="/libs/js/plugins/forms/wysihtml5/wysihtml5.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/forms/wysihtml5/toolbar.js"></script>

	<script type="text/javascript" src="/libs/js/plugins/interface/daterangepicker.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/fancybox.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/moment.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/jgrowl.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/datatables.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/colorpicker.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/fullcalendar.min.js"></script>
	<script type="text/javascript" src="/libs/js/plugins/interface/timepicker.min.js"></script>
    <script src="/assets/js/bootstrap-datetimepicker.min.js"></script>  
	<!--<script src="/libs/datatables/js/jquery.dataTables.js"></script>   --> 
	<script type="text/javascript" src="/libs/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/libs/js/bootbox/bootbox.js"></script>	
	<script type="text/javascript" src="/libs/js/application.js"></script>	
	<script type="text/javascript" src="/libs/validation/bootstrapValidator.js"></script>	

	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->headScript() ?>    	
</body>
</html>