<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
<title> Angeles Verdes</title>

<link href="/libs/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/libs/css/londinium-theme.css" rel="stylesheet" type="text/css">
<link href="/libs/css/styles.css" rel="stylesheet" type="text/css">
<link href="/libs/css/icons.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>

<script type="text/javascript" src="/libs/js/plugins/charts/sparkline.min.js"></script>

<script type="text/javascript" src="/libs/js/plugins/forms/uniform.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/select2.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/inputmask.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/autosize.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/inputlimit.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/listbox.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/multiselect.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/validate.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/tags.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/switch.min.js"></script>

<script type="text/javascript" src="/libs/js/plugins/forms/uploader/plupload.full.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/uploader/plupload.queue.min.js"></script>

<script type="text/javascript" src="/libs/js/plugins/forms/wysihtml5/wysihtml5.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/forms/wysihtml5/toolbar.js"></script>

<script type="text/javascript" src="/libs/js/plugins/interface/daterangepicker.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/fancybox.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/moment.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/jgrowl.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/datatables.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/colorpicker.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/fullcalendar.min.js"></script>
<script type="text/javascript" src="/libs/js/plugins/interface/timepicker.min.js"></script>

<script type="text/javascript" src="/libs/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/libs/js/application.js"></script>
<script src="/js/modules/login/login.js" type="text/javascript"></script>

<script type="text/javascript">
    /*$(function() {
        $('.aceptar').hover(function() {
            jQuery('.aceptar').addClass("aceptar_hover");
        },
        function() {
            jQuery('.aceptar').removeClass("aceptar_hover");
        });
    });*/
</script>
</head>

<body class="full-width page-condensed">
	<!-- Login wrapper -->
	<div class="login-wrapper">
    	<form action="#" role="form">
			<div class="popup-header">
				<!--<a href="#" class="pull-left"><i class="icon-user-plus"></i></a>-->
				<span class="text-semibold">Iniciar sesión</span>
				<!--
				<div class="btn-group pull-right">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cogs"></i></a>
                    <ul class="dropdown-menu icons-right dropdown-menu-right">
						<li><a href="#"><i class="icon-people"></i> Change user</a></li>
						<li><a href="#"><i class="icon-info"></i> Forgot password?</a></li>
						<li><a href="#"><i class="icon-support"></i> Contact admin</a></li>
						<li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                    </ul>
				</div>
				-->
			</div>
			<div class="well">
				<div id="divpErrorLogin" style="display:none;" class="alert alert-block alert-danger fade in block-inner">					
					<h6><i class="icon-cancel-circle"></i> !Error¡</h6>
					<hr>
					<p  id="pErrorLogin"></p>
				</div>				
			  	<!--<div id="divpErrorLogin" class="jGrowl" style="display:none;margin: 5px;">
		            <div class="jGrowl-notification growl-error">
			            <div class="jGrowl-close">×</div>
			            <div class="jGrowl-header">Error!</div>
			            <div class="jGrowl-message">
							<div id="pErrorLogin"></div>
			            </div>
		            </div>  
			  	</div>  -->		  

				<div class="form-group has-feedback">
					<label>Usuario</label>
					<input id="inputUser" name="inputUser" type="text" class="inputSend form-control" placeholder="Usuario">
					<i class="icon-users form-control-feedback"></i>
				</div>

				<div class="form-group has-feedback">
					<label>Contraseña</label>
					<input  id="inputPassword" name="inputPassword" type="password" class="inputSend form-control" placeholder="Contraseña">
					<i class="icon-lock form-control-feedback"></i>
				</div>

				<div class="row form-actions">
					<div class="col-xs-6">
						<div class="checkbox checkbox-success">
						<label>
							<input type="checkbox" class="styled"  id="datos" value="datos" name="datos" >
							Recordar Datos
						</label>
						</div>
					</div>

					<div class="col-xs-6">
						<button type="button"  onClick="validateLogin()" class="btn btn-warning pull-right"> Entrar</button>
					</div>
				</div>
			</div>
    	</form>
	</div>  
	<!-- /login wrapper -->


    <!-- Footer --
    <div class="footer clearfix">
        <div class="pull-left">&copy; 2013. Londinium Admin Template by <a href="http://themeforest.net/user/Kopyov">Eugene Kopyov</a></div>
    	<div class="pull-right icons-group">
    		<a href="#"><i class="icon-screen2"></i></a>
    		<a href="#"><i class="icon-balance"></i></a>
    		<a href="#"><i class="icon-cog3"></i></a>
    	</div>
    </div>
    /footer -->
</body>
</html>