<?php $this->headScript()->appendFile('/js/modules/general/gralTables.js') ?> 
<?php $this->headScript()->appendFile('/js/modules/general/jsImportFunctions.js') ?>   
<?php $disabled   = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?> 
<?php $urlActions = ($this->DbmanInfo['CUSTOM_ACTIONS']==1) ? $this->DbmanInfo['CUSTOM_URL'].'?catId=' : '/dbman/main/getdatainfo?ssIdource='.$this->DbmanInfo['CLAVE_MODULO'].'&catId='; ?>
    <input type="hidden" id="inputModule" value="<?php echo $this->DbmanInfo['CLAVE_MODULO']; ?>"/>
    <input type="hidden" id="inputDelete" value="-1"/>

    <div class="breadcrumb-line margin-t5px">
        <ul class="breadcrumb">
            <li>Administración</li>
            <li><?php echo $this->DbmanInfo['TITULO']; ?></li>
        </ul>
    </div>

    <div class="panel panel-default margin-t5px"  id="divBodyPage" >
        <div class="panel-heading">
            <h6 class="panel-title"> <?php echo $this->DbmanInfo['NOMBRE']; ?> Registrad@s </h6>
        </div>
        
        <div class="panel-body">
            <div class="col-md-12">
                <?php if($this->dataUser['INSERTAR']==1 && $this->DbmanInfo['AGREGAR']==1): ?>                                
                    <a href="<?php echo $urlActions.'-1'; ?>" class="btn btn-success tooltip-success white">
                       <i class="icon-plus-circle"></i> Agregar 
                    </a>

                    <?php if($this->DbmanInfo['IMPORTAR']==1):?>
                        <input type="hidden" id="inputImport" name="inputImport" value="<?php echo $this->DbmanInfo['URL_IMPORTADOR'];?>"/>
                        <a href="javascript:importData();" class="btn btn-warning tooltip-success white">
                           <i class="icon-upload3"></i> Importar
                        </a>                    
                    <?php endif;?>
                <?php endif;?>                    
            </div>
            <div class="datatable">
                <table class="table table-striped table-hover table-bordered" id="dataTable">
                    <thead> 
                        <tr>
                            <?php for($i=0;$i<count($this->aTittles);$i++):?>
                                <th>
                                    <?php echo $this->aTittles[$i];?>
                                </th>
                            <?php endfor;?>
                            <th class="col-xs-2 col-md-2">
                                Opciones
                            </th>
                        </tr>                                
                    </thead>                        
                    <tbody>                      
                        <?php foreach($this->aDataTable as $key => $items):?>
                            <tr>
                                <?php for($i=0;$i<count($this->aNamesTable);$i++):?>
                                    <?php $nameField = "".$this->aNamesTable[$i]; ?>
                                    <?php if($nameField!="ID"):?>
                                        <td><?php echo $items[$nameField];?> </td>
                                    <?php endif;?>
                                <?php endfor;?>
                                <td>
                                    <?php if($this->dataUser['LECTURA']==1 && $this->DbmanInfo['LECTURA']==1): ?>
                                        <a class="btn btn-warning" href="<?php echo $urlActions.$items['ID'] ?>" data-toggle="tooltip" data-placement="bottom" data-original-title="Ver"><i class="icon-eye"></i></a>
                                    <?php endif;?>                                    
                                    <?php if($this->dataUser['EDITAR']==1 && $this->DbmanInfo['MODIFICAR']==1): ?>
                                        <a class="btn btn-info btn-sm icon-only white tooltip-info" href="<?php echo $urlActions.$items['ID'] ?>" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="icon-pencil3"></i></a>                                                
                                    <?php endif;?> 
                                    <?php if($this->dataUser['ELIMINAR']==1 && $this->DbmanInfo['ELIMINAR']==1): ?>
                                        <a class="btn btn-danger btn-sm icon-only white tooltip-danger" onclick="beforeDelete('<?php echo $items['ID']; ?>')" data-toggle="tooltip" data-placement="bottom" data-original-title="Eliminar"><i class="icon-minus-circle"></i></a>
                                    <?php endif;?>

                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="myModalImport" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"> Importar <?php echo $this->DbmanInfo['TITULO']; ?></h4>
                </div>

                <div class="modal-body with-padding">
                    <img id="loader" class="col-xs-offset-4" src="/assets/images/loading.gif" alt="loading gif"/>          
                    <iframe class="hmodal550" id="iFrameImport" src="" style="zoom:0" frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>        