<?php $this->headScript()->appendFile('/js/modules/atn/mainAtnSearch.js') ?>  
	<div class="panel panel-default"  style="display:<?php echo ($this->showForm==0) ? 'block' : 'none';?>">    
	    <div class="panel-body">
			<form method="POST" action="/atn/main/searchcitas" id="FormData" class="form-horizontal ">
				<input type="hidden" id="opSearch" name="opSearch"  value="search"/>

				<div class="col-xs-12">
					<div class="col-xs-6">
				        <div class="form-group">
				            <label class="col-sm-2 control-label text-right">Inicio<span class="required">*</span></label>
				            <div class="col-sm-10">
				            	<input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control">
				            </div>
				        </div>
					</div>
					<div class="col-xs-6">
				        <div class="form-group">
				            <label class="col-sm-2 control-label text-right">Fin<span class="required">*</span></label>
				            <div class="col-sm-10">
				            	<input readonly id="inputFechaFin" name="inputFechaFin" data-required="1"  type="text" class="form-control">
				            </div>
				        </div>
					</div>
				</div>

				<div class="col-xs-12">
					<div class="col-xs-6">
				        <div class="form-group">
				            <label class="col-sm-2 control-label text-right">Buscar<span class="required">*</span></label>
				            <div class="col-sm-10">
				            	 <input id="inputSearch" name="inputSearch" data-required="1"  place-holder="(nombre Cliente, telófono)" type="text" class="form-control">
				            </div>
				        </div>
					</div>
					<div class="col-xs-6">
				        <div class="form-group">
				            <label class="col-sm-2 control-label text-right">Estatus </label>
				            <div class="col-sm-10">
								<select class="span4 m-wrap" id="inputEstatus" name="inputEstatus">
									<option value="">Seleccionar una opción</option>													
									<?php echo $this->Status;?>
								</select>
				            </div>
				        </div>
					</div>
				</div>	
				<div class="form-actions text-right">
                	<input type="submit" class="btn bnt-info" value="Buscar">
                </div>
			</form>
	    </div>
	</div>
	<!-- block -->

	<div class="panel panel-default margin-t5px"  style="display:<?php echo ($this->showForm==1) ? 'block' : 'none';?>">
	    <div class="panel-heading">
			<div class="pull-left">
				<a href="/atn/main/searchcitas">
					<button class="btn btn-default btn-sm" type="button" onClick="searchDialog();" ><i class="icon-arrow-left5"></i>Regresar</button>
				</a>
			</div>
	    </div>
	    
	    <div class="panel-body">
			<div class="datatable">
	            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
	                <thead>
	                    <tr>
	                    	<th>Estatus</th>
	                        <th>Fecha/Hora</th>
	                        <th>Contacto</th>
	                        <th>Tel.Contacto</th>
	                        <th>Cliente</th>
	                        <th>Dirección</th>
	                        <th></th>
	                    </tr>
	                </thead>
	                <tbody>                                
	                    <?php foreach($this->dataSearch as $key => $items): ?>  
	                    <tr class="odd gradeX">
	                        <td><?php echo $items['ESTATUS']; ?></td>
	                        <td><?php echo $items['FECHA_CITA']." ".$items['HORA_CITA']; ?></td>
	                        <td><?php echo $items['CONTACTO'] ?></td>
	                        <td><?php echo $items['TELEFONO_CONTACTO']; ?></td>
	                        <td><?php echo $items['NOMBRE_CLIENTE']; ?></td>
	                        <td><?php echo $items['DIRECCION_CITA'] ?></td>
	                        <td class="text-center">                                
	                            <a href="javascript:parent.showDetail(<?php echo $items['ID_CITA'];?>)">
	                            	<button class="btn btn-info btn-sm"> <i class="icon-redo2"></i></button></a>
	                        </td>
	                    </tr>    
	                    <?php endforeach;?>                                             
	                </tbody>
	            </table>	
            </div>    	
	    </div>