<?php $this->headScript()->appendFile('/libs/datatables/js/dataTables.fixedColumns.min.js'); ?>
<?php $this->headScript()->appendFile('/libs/others/jQuery.print.js'); ?>
<?php $this->headScript()->appendFile('/js/reports/jsServicesReports.js'); ?>
<?php $this->headScript()->appendFile('/js/modules/general/functionGral.js'); ?>
<div id="divDataPersonal" class="hide"><?php foreach($this->aTecnicos as $key => $items):?><?php echo ($control==0) ? '': '?';?><?php echo $items['ID']."|".$items['NAME']."|".$items['ID_SUCURSAL'];?><?php $control++;?><?php endforeach;?></div>

<div class="panel panel-default margin-t5px">
    <div class="panel-heading">
        <h6 class="panel-title"> Reporte de Actividades</h6>
    </div>
    
    <div class="">
        <div class="row no-margin-l  margin-t5px">
            <form method="POST" action="/reports/activities/index" id="FormData" class="form-horizontal formcustom">
                <input type="hidden" name="optReg" value="search" />
                <input type="hidden" name="inputStatus" id="inputStatus" value="<?php echo $this->iStatus; ?>" />
                <fieldset> 
                    <div class="col-md-12">   
                        <div class="col-md-4">
                            <div class="control-group">
                                <label class="control-label">Fecha Inicio<span class="required">*</span></label>
                                <div class="controls">
                                    <input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputFechaIn']; ?>">
                                </div>
                            </div>                             
                        </div>
                        <div class="col-md-4">
                            <div class="control-group">
                                <label class="control-label">Fecha Fin<span class="required">*</span></label>
                                <div class="controls">
                                    <input readonly type="text" id="inputFechaFin" name="inputFechaFin" class="form-control" value="<?php echo (@$this->data['inputFechaFin']); ?>">                          
                                </div>
                            </div>  
                        </div>
                        <div class="col-md-4">                                     
                            <div class="control-group">
                                <label class="control-label">Sucursal <span class="required">*</span></label>
                                <div class="controls">
                                    <select class="chzn-select col-md-10" id="cboInstalacion" name="cboInstalacion" onChange="getoptionsSimpleCbo('Unidad','munidades',this.value,false,'');getoptionsSimpleCbo('Usuario','musuarios',this.value,false,'');">
                                        <option value="-1">Todos</option>
                                        <?php echo $this->cInstalaciones;?>
                                    </select>
                                </div>
                            </div>
                        </div>    
                    </div>  
                    <div class="col-md-12 no-margin-l"  style="margin-bottom: 10px">
                        <div class="col-md-4">       
                            <div class="control-group">
                                <label class="control-label">Unidad <span class="required">*</span></label>
                                <div class="controls">
                                    <div id="divUnidad"></div>   
                                    <select class="chzn-select col-md-10" id="inputUnidad" name="inputUnidad" onChange="getReport()">
                                        <option value="-1">Todos</option>
                                        <?php echo $this->cUnidades;?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                             <div class="control-group">
                                <label class="control-label">Usuario <span class="required">*</span></label>
                                <div class="controls">
                                    <div id="divUsuario"></div>   
                                    <select class="chzn-select col-md-10" id="inputUsuario" name="inputUsuario" onChange="getReport()">
                                        <option value="-1">Todos</option>
                                        <?php echo $this->cUsuarios;?>
                                    </select>
                                </div>
                            </div>                      
                        </div>
                        <div class="col-md-4">
                            <div class="control-group">
                                <label class="control-label"></label>
                                <div class="controls">
                                    <button type="submit" class="btn row-margin-r5 btn-primary">Buscar</button>
                                </div>
                            </div>                            
                        </div> 
                    </div>                          
                </fieldset>
            </form>
        </div>
    </div>    
</div>
<div class=" no-margin-l  margin-t5px">      
    <div class="pull-right">
        <?php if(count($this->aData)>0): ?>
            <div class="text-center">
                <a target="_blank" href="/reports/activities/exportdata?inputFechaIn=<?php echo @$this->data['inputFechaIn'];?>&inputFechaFin=<?php echo @$this->data['inputFechaFin'];?>&cboInstalacion=<?php echo @$this->data['cboInstalacion']; ?>&inputUsuario=<?php echo $this->iUsuario;?>&inputUnidad=<?php echo $this->iUnidad;?>">
                    <button data-toggle="tooltip" data-placement="bottom" title="Exportar a Excel"  type="button" class="btn btn-success"><i class="icon-file-excel"></i> XLS</button>
                </a>
                <a target="_blank" href="/reports/activities/exportkml?inputFechaIn=<?php echo @$this->data['inputFechaIn'];?>&inputFechaFin=<?php echo @$this->data['inputFechaFin'];?>&cboInstalacion=<?php echo @$this->data['cboInstalacion']; ?>&inputUsuario=<?php echo $this->iUsuario;?>&inputUnidad=<?php echo $this->iUnidad;?>">
                    <button data-toggle="tooltip" data-placement="bottom" title="Exportar a KML"  type="button" class="btn btn-info"><i class="icon-map"></i> KML</button>
                </a>                
            </div>
        <?php endif;?>
    </div>                          
</div>
<div class="datatable-tools">                     
    <table cellspacing="0" width="100%" class="table table-striped table-bordered display"  id="dataTable">
        <thead>             
            <tr>
                <th>Jefatura</th>
                <th>Unidad</th>
                <th>Usuario</th>
                <th>Técnico 2</th>                
                <th>Actividad</th>
                <th>Fecha</th>
                <th>Ubicación</th>                            
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php $result = '';$print=false?>
            <?php foreach($this->aData as $key => $items): ?>    
                <?php $results = explode("|",$items['N_UNIDAD']);?>
                    <tr>
                        <td><?php echo $items['N_SUCURSAL'];?></td>
                        <td><?php echo @$results[0];?></td>                        
                        <td><?php echo $items['N_USUARIO'];?></td>
                        <td><?php echo @$results[1];?></td>
                        <td><?php echo $items['N_ACTIVIDAD'];?></td>
                        <td><?php echo $items['FECHA_CAPTURA_EQUIPO'];?></td>
                        <td><?php echo $items['UBICACION'];?></td>
                        <td>
                            <?php if(isset($items['LATITUD'])  && $items['LATITUD']!="" && 
                                     isset($items['LONGITUD']) && $items['LONGITUD']!="" 
                                    ):?>
                                <div class="text-center">                                
                                    <button onClick="getUbicacion(<?php echo $items['ID_RESULTADO'];?>)" data-toggle="tooltip" data-placement="bottom" title="Ver en Mapa" type="button" class="btn btn-icon btn-primary"><i class="icon-globe2"></i></button>
                                </div>
                            <?php endif;?>
                        </td>
                    </tr>  
            <?php  endforeach;?>
        </tbody>
    </table>                  
</div>

<div id="myModalMapa" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"> Ubicación </h4>
            </div>

            <div class="modal-body with-padding">
                <img id="loader" class="col-xs-offset-4" src="/assets/images/loading.gif" alt="loading gif"/>          
                <iframe class="hmodal550" id="iFrameModalMapa" src="" style="zoom:0" frameborder="0"></iframe>
            </div>
        </div>
    </div>
</div>