<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places'); ?>
<?php $this->headScript()->appendFile('/js/modules/general/functionGral.js') ?> 
<?php $this->headScript()->appendFile('/libs/upload/jasny-bootstrap.min.js') ?>
<?php echo $this->headLink()->appendStylesheet('/libs/upload/jasny-bootstrap.min.css'); ?>
<?php $this->headScript()->appendFile('/js/modules/geos/jsValidateImport.js') ?> 
<input type="hidden" id="inputToken" name="inputToken" value="<?php echo $this->aToken;?>">
<?php if(@$this->iOptionImport==-1):?>
<div class="col-md-12 m-top-3" align="center">      
    <form id="formOptions" class="form-horizontal" role="form" method="POST" action="/admin/geos/importdata"  enctype="multipart/form-data">
        <input type="hidden" id="optImp" name="optImp" value="<?php echo $this->iOptionImport; ?>" />
        <a href="javascript:setValueForm(1);" class="btn btn-success tooltip-success white">
           <i class="icon-pushpin"></i>Puntos
        </a>

        <a href="javascript:setValueForm(2);" class="btn btn-info tooltip-success white">
           <i class="icon-joomla"></i>Area
        </a>

        <a href="javascript:setValueForm(3);" class="btn btn-primary tooltip-success white">
           <i class="icon-wave"></i> Rutas
        </a>

    </form>
</div>

<?php elseif(@$this->iOptionImport==1):?>
    <br/> <br/>    
    <form id="formDbman" class="form-horizontal" role="form" method="POST" action="/admin/geos/uploadfilepoints"  enctype="multipart/form-data">                            
        <input type="hidden" id="optReg" name="optReg" value="uploadFile" />
        <input type="hidden" id="optImp" name="optImp" value="<?php echo $this->iOptionImport; ?>" />
        <p align="center" style="font-weight:bold; font-size:15px;">
            <span>1.- Descargar plantilla. <a target="_blank" href="/plantilla/plantilla.xlsx"><i class="icon-file-download"></i></a> </span> <br/> <br/>
            <span>2.- Llenar la información.</span> <br/>
            <img src="/images/upload_file.png" ><br/> <br/>
            <span>2.- Subir Layout con información.</span> <br/> <br/>

            <div class="col-md-12" align="center">
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="col-md-5">
                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 130px; height: 50px; line-height: 150px;"></div>
                    </div>
                    <div class="col-md-7">
                        <span class="btn btn-default btn-file">
                        <span class="fileinput-new">Seleccionar Archivo</span>
                        <span class="fileinput-exists">Cambiar</span>
                        <input type="file" name="imageProfile" accept=".xls,.xlsx"></span>
                        <a href="#" class="btn btn-default fileinput-exists  col-md-5" data-dismiss="fileinput">Eliminar</a>
                    </div>
                </div>
                <input type="submit" value="Subir" class="btn btn-primary tooltip-success white" id="btnSend">
            </div>            
        </p>
    </fom>
<?php else:?>

<?php endif;?>