<?php $this->headScript()->appendFile('/js/modules/general/gralTables.js') ?>
<?php $this->headScript()->appendFile('/js/modules/geos/jsResultImport.js') ?> 
<div class="col-md-12 m-top-3" align="center">     
	<h3>Se ha procesado el archivo 
		<div class="pull-right">
		<a href="/admin/geos/importdata" class="btn btn-success tooltip-success white">
			Importar otro Archivo
        </a>
	</div></h3>
	
	<div class="col-md-6 col-md-offset-3" align="center">
		<table class="table table-striped table-hover table-bordered">
			<tr>
				<td>Total de Registros Procesados</td><td><?php echo $this->iProcess;?></td>
			</tr>
			<tr>
				<td>Registros Correctos</td><td><?php echo ($this->iProcess - count($this->iErrors));?></td>
			</tr>		
			<tr>
				<td>Registros Incorrectos</td><td><?php echo count($this->iErrors);?></td>
			</tr>				
		</table>
	</div>	

	<?php if(count($this->iErrors)>0):?>
		<table class="table table-striped table-hover table-bordered" id="dataTable">
		<thead>
			<tr>
				<th>No. Linea</th>
				<th>Problema</th>				
			</tr>
		</thead>
		<tbody>		
		<?php foreach($this->iErrors as $key => $items):?>

			<tr>
				<td><?php echo $items['linea'];?></td>
				<td><?php echo $items['errors'];?></td>
			</tr>
		<?php endforeach;?>
			</tbody>
		</table>
	<?php endif;?>	
</div>