 <?php $this->headScript()->appendFile('/js/modules/callcenter/lastStepCall.js') ?>  
<div class="breadcrumb-line margin-t5px">
    <ul class="breadcrumb">
        <li><a href="/callcenter/callservice/index">Datos del Cliente</a></li>
        <li><a href="/callcenter/callservice/instalation">Ubicación de la Instalación</a></li>
        <li><a href="/callcenter/callservice/cardetail">Datos del Vehículo</a></li>
        <li><a href="javascript:void()">Fecha de la Cita</a></li>
    </ul>
</div> 

 <div class="panel panel-default margin-t5px"  id="divBodyPage" >
        <div class="panel-heading">
            <h6 class="panel-title"> Fecha de la Cita</h6>
        </div>
        
        <div class="panel-body">
            <div class="col-xs-12">
				<form method="POST" action="/callcenter/callservice/datefinish" id="FormData" class="form-horizontal ">
                	<input type="hidden" name="optReg" value="new" />
					<fieldset>
						<?php if($this->error):?>
							<div class="alert alert-error">
								<button class="close" data-dismiss="alert">&times;</button>
								<strong>Error!</strong> Ocurrio un error al guardar la información, Favot de intentar mas tarde.
							</div>
						<?php  endif;?>



						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label">Dia de Instalación</label>
									<div class="col-sm-9">
				                          <input readonly id="inputDate" name="inputDate" type="text" class="form-control" value="<?php echo @$this->data['inputDate']; ?>" >
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
														
							</div>						
						</div>	

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label">Técnicos</label>
									<div class="col-sm-9">										
										<select class="col-xs-10" id="inputTecnico" name="inputTecnico" onChange="getHorariosCbo(this.value)">
											<option value="">Seleccionar una opción</option>
											<?php echo $this->aTecnicos; ?>
										</select>								
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label">Horarios Disponibles</label>
									<div class="col-sm-9">
										<div id="divhorario"></div>
										<select class="col-xs-10" id="inputhorario" name="inputhorario">
											<option value="">Seleccionar una opción</option>
										</select>										
									</div>
								</div>							
							</div>						
						</div>	

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group">
									<label class="col-sm-3 control-label">Contacto<span class="required">*</span></label>
									<div class="col-sm-9">
				                          <input id="inputContacto" name="inputContacto" data-required="1"  type="text" class="form-control upper" value="<?php echo @$this->data['inputContacto']; ?>" >
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="control-group">
									<label class="col-sm-3 control-label">Teléfono<span class="required">*</span></label>
									<div class="col-sm-9">
										<input type="tel" id="inputTelContacto" data-required="1" name="inputTelContacto" class="form-control upper" value="<?php echo (@$this->data['inputTelContacto']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>					

						<div class="col-xs-12">
					    	<div class="">
								<div class="pull-right">	
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>		
									<button type="submit" class="btn btn-default bg-btn-send">Terminar</button>
								</div>    
					    	</div>						
						</div>						
					</fieldset>	                	
                </form>	            	
            </div>
        </div>
	</div>