 <?php $this->headScript()->appendFile('/js/modules/callcenter/newservice.js') ?>   
 <?php $this->headScript()->appendFile('/js/modules/general/functionGral.js') ?> 
    <div class="panel panel-default margin-t5px"  id="divBodyPage" >
        <div class="panel-heading">
            <h6 class="panel-title"> Datos generales del Cliente</h6>
        </div>
        
        <div class="panel-body">
            <div class="col-xs-12">
				<form method="POST" action="/callcenter/callservice/index" id="FormData" class="form-horizontal" >
                	<input type="hidden" id="inputOpr"    name="optReg" value="new" />
					<input type="hidden" id="typeSearch"  name="typeSearch"  value="" />
					<input type="hidden" id="inputSearch" name="inputSearch" value="" />
					<fieldset>
						<div class="row col-xs-12 ">
							<div class="col-xs-6">
	                            <div class="form-group no-margin-b">
	                                <label for="inputTitulo" class="col-sm-3 control-label"><span class="mandatory">*</span> Tipo Cliente</label>
	                                <div class="col-sm-9">
	                                    <select class="col-xs-10 form-control" id="inputTipo" name="inputTipo" onChange="changeTypePerson(this.value)" onClick="changeTypePerson(this.value)">
												<option value="">Seleccionar una opción</option>													
												<?php echo $this->tipoCliente;?>
											</select>
	                                </div>
	                            </div>		
							</div>
							<div class="col-xs-6">
	                            <div class="form-group no-margin-b">
	                                <label for="inputTitulo" class="col-sm-3 control-label"><span class="mandatory">*</span> Tipo Servicio</label>
	                                <div class="col-sm-9">
	                                    <select class="col-xs-10 form-control" id="inputTipService" name="inputTipService">
											<option value="">Seleccionar una opción</option>													
											<?php echo $this->tipoService;?>
										</select>
	                                </div>
	                            </div>							
							</div>						
						</div>
						<div class="row col-xs-12 divMoral" style="display:<?php echo (@$this->data['inputTipo']=='M' ) ? 'block': 'none';?>;">
							<div class="col-xs-6">
	                            <div class="form-group no-margin-b">
	                                <label for="inputTitulo" class="col-sm-3 control-label"><span class="mandatory">*</span> RFC</label>
	                                <div class="col-sm-9">
	                                    <input id="inputRFC" name="inputRFC" type="text" class="form-control upper" value="<?php echo @$this->data['inputRFC']; ?>" >
	                                </div>
	                            </div>		
							</div>
							<div class="col-xs-6">
	                            <div class="form-group no-margin-b">
	                                <label for="inputTitulo" class="col-sm-3 control-label"><span class="mandatory">*</span> Razón Social</label>
	                                <div class="col-sm-9">
	                                    <input id="inputRazon" name="inputRazon" type="text" class="form-control upper" value="<?php echo @$this->data['inputRazon']; ?>" >
	                                </div>
	                            </div>							
							</div>	
						</div>

						<div class="row col-xs-12 divMoral" style="display:<?php echo (@$this->data['inputTipo']=='M' ) ? 'block': 'none';?>;">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label for="inputTitulo" class="col-sm-3 control-label">Clave Cliente</label>
									<div class="col-xs-9">
										<input type="text" id="inputClave" name="inputClave" class="form-control upper" value="<?php echo (@$this->data['inputClave']); ?>"  >
									</div>
								</div>
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">

								</div>
							</div>									
						</div>		

						<div class="row col-xs-12 ">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span>  Nombre(s)</label>
									<div class="col-xs-9">
				                        <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNombre']; ?>" >
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Apellidos</label>
									<div class="col-xs-9">
										<input type="text" id="inputApps" name="inputApps" class="form-control upper" value="<?php echo (@$this->data['inputApps']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>						

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label">Fecha de Nacimiento</label>
									<div class="col-xs-9">
				                          <input id="inputNac" readonly name="inputNac"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNac']; ?>" data-date-format="YYYY-MM-DD">
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Género</label>
									<div class="col-sm-9">
										<select class="col-xs-10 form-control" id="inputGenero" name="inputGenero">
											<option value="">Seleccionar una opción</option>													
											<?php echo $this->genero;?>
										</select>
									</div>
								</div>							
							</div>						
						</div>

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Teléfono Fijo </label>
									<div class="col-sm-9">
				                          <input id="inputTel" name="inputTel" data-required="1"  type="tel" class="form-control upper" value="<?php echo @$this->data['inputTel']; ?>" >
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Teléfono móvil </label>
									<div class="col-sm-9">
										<input type="text" id="inputCel" name="inputCel" class="form-control upper" value="<?php echo (@$this->data['inputCel']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Correo electrónico</label>
									<div class="col-sm-9">
				                          <input id="inputEmail" name="inputEmail" data-required="1"  type="email" class="form-control" value="<?php echo @$this->data['inputEmail']; ?>" >
									</div>
								</div>							
							</div>	
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Confirmar correo</label>
									<div class="col-sm-9">
				                          <input id="inputEmailConf" name="inputEmailConf" data-required="1"  type="email" class="form-control" value="<?php echo @$this->data['inputEmailConf']; ?>" >
									</div>
								</div>							
							</div>													
						</div>
						<div class="row col-xs-12">
							<div class="col-xs-12">
								<div class="form-group no-margin-b">
									<label class="col-sm-2 control-label"><span class="mandatory">*</span> Calle</label>
									<div class="col-sm-12">
										<input type="text" id="inputStreet" name="inputStreet" class="col-xs-9 form-control upper" value="<?php echo (@$this->data['inputRefsO']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>	

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> No. Ext</label>
									<div class="col-sm-9">
				                          <input id="inputNoExt" name="inputNoExt" data-required="1"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNoExt']; ?>" >
									</div>
								</div>				
							</div>
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> No. Int</label>
									<div class="col-sm-9">
										<input type="text" id="inputNoInt" name="inputNoInt" class="form-control upper" value="<?php echo (@$this->data['inputNoInt']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>	

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> C.P</label>
									<div class="col-sm-9">
										<input type="text" id="inputCP" name="inputCP" class="form-control upper" value="<?php echo (@$this->data['inputCP']); ?>"  >
									</div>
								</div>							
							</div>						
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<button type="button" class="btn btn-default bg-btn-send" onClick="searchCp(0)">Buscar por CP</button>
								</div>				
							</div>							
						</div>		


						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Estado</label>
									<div class="col-sm-9">
										<select class="col-xs-10 upper" id="inputEstado" name="inputEstado" onChange="getoptionsCbo('Municipio','mun',this.value,false,'colonia');">
											<option value="">Seleccionar una opción</option>
											<?php echo $this->estados; ?>
					                    </select>
									</div>
								</div>							
							</div>											
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Municipio</label>
									<div class="col-sm-9">
										<div id="divMunicipio"></div>												
										<select class="col-xs-10 upper" id="inputMunicipio" name="inputMunicipio" onChange="getoptionsCbo('colonia','colonia',this.value,false,'');">
											<option value="">Seleccionar una opción</option>
											<?php echo $this->municipios; ?>
										</select>
									</div>
								</div>				
							</div>					
						</div>

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Colonia</label>
									<div class="col-sm-9">
										<div id="divcolonia"></div>
										<select class="col-xs-10  upper" id="inputcolonia" name="inputcolonia" <?php echo (isset($this->data['inputcolonia'])) ? 'onChange(getCPdir(this.value,"colonia"))': '';?>>
											<option value="">Seleccionar una opción</option>
											<?php echo $this->colonias;?>
										</select>
									</div>
								</div>				
							</div>				
						</div>
						<div class="row col-xs-12">
							<div class="col-xs-12">
								<div class="form-group no-margin-b">
									<label class="col-sm-2 control-label"><span class="mandatory">*</span> Referencias</label>
									<div class="col-sm-12">
										<input type="text" id="inputRefs" name="inputRefs" class="col-xs-9 form-control upper" value="<?php echo (@$this->data['inputRefsO']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>													

						<div class="row col-xs-12">
							<div class="col-xs-6">
								<div class="form-group no-margin-b">
									<label class="col-sm-3 control-label"><span class="mandatory">*</span> Instalacion en Domicilio del Cliente</label>
									<div class="col-sm-9">
										<select class="col-xs-10" id="inputDom" name="inputDom" onChange="differentDom(this.value)">
											<?php echo $this->mismoDomicilio; ?>
					                    </select>	
									</div>
								</div>							
							</div>											
							<div class="col-xs-6">
								<div id="cboOptsDom" style="display:<?php echo (@$this->data['inputDom']==0 && isset($this->data['inputDom'])) ? 'display':'none';?>;">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> Domicilio de la instalación</label>
										<div class="col-sm-9">
											<select class="col-xs-10" id="inputDirDom" name="inputDirDom" onChange="showFormDirection(this.value);">
												<option value="0">Seleccionar una opción</option>
												<?php echo $this->dirDomicilio; ?>
						                    </select>
										</div>
									</div>				
								</div>
							</div>					
						</div>		

						<div id="divDifDom" style="display:<?php echo (@$this->data['inputDirDom']==2 && isset($this->data['inputDirDom']) && $this->inputDom==0) ? 'display':'none';?>;">
							<div class="row col-xs-12">
								<div class="col-xs-12">
									<div class="form-group no-margin-b">
										<label class="col-sm-2 control-label"><span class="mandatory">*</span> Calle</label>
										<div class="col-sm-12">
											<input type="text" id="inputStreetO" name="inputStreetO" class="col-xs-9 form-control upper" value="<?php echo (@$this->data['inputRefsO']); ?>"  >
										</div>
									</div>							
								</div>						
							</div>							
							<div class="row col-xs-12">
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> No. Ext</label>
										<div class="col-sm-9">
					                          <input id="inputNoExtO" name="inputNoExtO" type="text" class="form-control upper" value="<?php echo @$this->data['inputNoExtO']; ?>" >
										</div>
									</div>				
								</div>
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> No. Int</label>
										<div class="col-sm-9">
											<input type="text" id="inputNoIntO" name="inputNoIntO" class="form-control upper" value="<?php echo (@$this->data['inputNoIntO']); ?>"  >
										</div>
									</div>							
								</div>						
							</div>
							<div class="row col-xs-12">
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> C.P</label>
										<div class="col-sm-9">
											<input type="text" id="inputCPO" name="inputCPO" class="form-control upper" value="<?php echo (@$this->data['inputCPO']); ?>"  >
										</div>
									</div>							
								</div>						
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<button type="button" class="btn btn-default bg-btn-send" onClick="searchCp(1)">Buscar por CP</button>
									</div>				
								</div>							
							</div>		

							<div class="row col-xs-12">
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> Estado</label>
										<div class="col-sm-9">
											<select class="col-xs-10 upper" id="inputEstadoO" name="inputEstadoO" onChange="getoptionsCbo('MunicipioO','mun',this.value,false,'coloniaO');">
												<option value="">Seleccionar una opción</option>
												<?php echo $this->estadosO; ?>
						                    </select>
										</div>
									</div>							
								</div>											
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> Municipio</label>
										<div class="col-sm-9">
											<div id="divMunicipioO"></div>	
											<select class="col-xs-10 upper" id="inputMunicipioO" name="inputMunicipioO" onChange="getoptionsCbo('coloniaO','colonia',this.value,false,'');">
												<option value="">Seleccionar una opción</option>
												<?php echo $this->municipiosO; ?>
											</select>
										</div>
									</div>				
								</div>					
							</div>							

							<div class="row col-xs-12">
								<div class="col-xs-6">
									<div class="form-group no-margin-b">
										<label class="col-sm-3 control-label"><span class="mandatory">*</span> Colonia</label>
										<div class="col-sm-9">
											<div id="divcoloniaO"></div>	
											<select class="col-xs-10 upper" id="inputcoloniaO" name="inputcoloniaO" <?php echo (isset($this->data['inputcoloniaO'])) ? 'onChange="getCPdir(this.value,\'coloniaO\')"': '';?>>
												<option value="">Seleccionar una opción</option>
												<?php echo $this->coloniasO;?>
											</select>
										</div>
									</div>				
								</div>
								<div class="col-xs-6">					
								</div>						
							</div>

							<div class="row col-xs-12">
								<div class="col-xs-12">
									<div class="form-group">
										<label class="col-sm-2 control-label"><span class="mandatory">*</span> Referencias</label>
										<div class="col-sm-11">
											<input type="text" id="inputRefsO" name="inputRefsO" class="col-xs-9 form-control upper" value="<?php echo (@$this->data['inputRefsO']); ?>"  >
										</div>
									</div>							
								</div>						
							</div>							
						</div>				
						<div class="row col-xs-12">
								<div class="pull-right">
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>			
									<button type="submit" class="btn btn-default bg-btn-send">Continuar</button>
								</div>    
						</div>
					</fieldset>	                	
                </form>	
            </div>
        </div>
    </div>