 <?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
 <?php $this->headScript()->appendFile('/js/modules/callcenter/instalation.js') ?>   
   
<div class="breadcrumb-line margin-t5px">
    <ul class="breadcrumb">
        <li><a href="/callcenter/callservice/index">Datos del Cliente</a></li>
        <li>Ubicación de la Instalación</li>
    </ul>
</div>
    <div class="panel panel-default margin-t5px"  id="divBodyPage" >
        <div class="panel-heading">
            <h6 class="panel-title"> Ubicación de la Instalación </h6>
        </div>
        
        <div class="panel-body">
            <div class="col-xs-12">
            	<form method="POST" action="/callcenter/callservice/instalation" id="FormData" class="form-horizontal ">
                	<input type="hidden" name="optReg" value="new" />
					<fieldset>
						<input type="hidden" value="<?php echo $this->data['inputLatitude'];?>" id="inputLatitude"   name="inputLatitude"/>
						<input type="hidden" value="<?php echo $this->data['inputLongitude'];?>" id="inputLongitude" name="inputLongitude"/>
						<input type="hidden" value="<?php echo $this->dataService['inputDom'];?>" id="inputDom"/>
						<input type="hidden" value="<?php echo $this->dataService['inputDirDom'];?>" id="inputOtherDom"/>
						<input type="hidden" value="<?php echo $this->direccion; ?>" id="inputDir"/>
						<?php if($this->dataService['inputDirDom']==1 && $this->dataService['inputDom']==0):?>
	                    	<div id="tabInstalacion">
	                    		<fieldset>
										<div class="col-xs-12">
											<label class="col-xs-3">Seleccione centro de Atención</label>
											<select class="col-xs-5 " id="cboInstalacion" name="cboInstalacion" onChange="centerInstalacion(this.value)">
												<option value="">Seleccionar una opción</option>
						                        <?php foreach ($this->cInstalaciones as $key => $item): ?>
						                            <option value="<?php echo $item['ID_SUCURSAL']?>"><?php echo $item['DESCRIPCION']?></option>
						                        <?php endforeach; ?>
						                    </select>													
										</div>

										<?php foreach ($this->cInstalaciones as $key => $item): ?>
											<?php $varOptionC = $item['ID_SUCURSAL']."|".$item['DESCRIPCION']."|Cto. Heroes|25|1|Satelite|Naucalpan|Mexico|53100|".$item['LATITUD']."|".$item['LONGITUD']; ?>
				                        	<input type="hidden" id="txt<?php echo $item['ID_SUCURSAL'];?>" value="<?php echo $varOptionC; ?>">
				                        <?php endforeach; ?>
				                        
	                    		</fieldset>
	                    	</div>
						<?php endif;?>
                    	<div id="tabMap" class="m-top-1">
                    		<?php if($this->dataService['inputDirDom']== 2 || $this->dataService['inputDom']==1):?>
								<div class="col-xs-11">Ubique la dirección en el Mapa. Puede arrastrar o dar click para tener mayor precisión</div>
                    		<?php endif;?>

                    		<div class="block-content">                    			
                    			<?php if($this->dataService['inputDirDom']==1 && $this->dataService['inputDom']==0):?>
	                    			<div class="col-xs-3">
	                    				<div id="dataCentro" class="row-min-h300">
	                    					<h3>Seleccione un Centro de Instalación</h3>
	                    				</div>
	                    			</div>
                    			<?php endif;?>
								
                    			<div class="<?php echo ($this->dataService['inputDirDom']== 2 || $this->dataService['inputDom']==1) ? 'col-xs-12': 'col-xs-9';?> ">
		                        	<div id="myMapDraw" style="width:100%;height:350px;">

		                        	</div>
                    			</div>
                    			
                    		</div>
                    	</div>	
                    	
						<div class="col-xs-12">
					    	<div class="m-top-1">
								<div class="pull-right">			
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>
									<button type="submit" class="btn btn-default bg-btn-send">Continuar</button>
								</div>    
					    	</div>						
						</div>						
					</fieldset>	  
                </form>	

            </div>
        </div>
     </div>